<?php

namespace common\components\reports;
use kartik\mpdf\Pdf;

/**
 * This is Pdf report Generator Component using mPdF extension from Krajee
 *
 */

class PdfGenerator {


	public function generatePdf($content,$title=null, $header=null,$footer=null,$settings=[])
	{
		$system= \Yii::$app->name;
		
		if(!isset($title))
		$title='Report by: '.$system;
		
		if (!isset($header))
		$header = 'Generated by '.$system.' On '.date("d-M-Y :h:i:sa");

		if(!isset($footer))
        $footer = '|Page {PAGENO}|';

		$pdf = new Pdf([
        // set to use core fonts only
        'mode'=> isset($settings['mode']) ? $settings['mode'] : Pdf::MODE_CORE, 
        
        // A4 paper format
        'format' => isset($settings['format']) ? $settings['format'] : Pdf::FORMAT_A4, 

        // portrait orientation
        'orientation' => isset($settings['orientation']) ? $settings['orientation'] : Pdf::ORIENT_PORTRAIT,

        // stream to browser inline
        'destination' =>  isset($settings['destination']) ? $settings['destination'] : Pdf::DEST_BROWSER, 

        // your html content input
        'content' => $content,  
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting 
        'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}', 
         // set mPDF properties on the fly
        'options' => ['title' => $title ],
         // call mPDF methods on the fly
        'methods' => [ 

            'SetHeader'=>[$header], 
            'SetFooter'=>[$footer],
        ]
    ]);
	    // return the pdf output as per the destination setting
	    return $pdf->render(); 
	}

}

