<?php
 /**
  * This footer file has to be included in all custom html mail templates
  *
  */
?>
  </div><!--cell content ends -->
    </div> <!--cell ends -->
    	</div> <!--- main row ends -->
    	<div class="footer row"> 
       <div class='footercell'>
          <p> This is an autogenerated mail and the sender or the development team doesnot guarantee that the mail is free of any malware, objectionable or damaging content. The views expressed herein no way represents CCMT but solely belong to the sender.</p>
          <hr/>
          <p>Mail is sent by CCMT Centre Reporting System team. <br/>&copy Central Chinmaya Mission Trust 2017 - 2018 </p>
        </div>
      </div>
   </div>