<?php
 /**
  * This footer file has to be included in all custom html mail templates
  *
  */
?>
  </div>
    </div>
    	</div>
    	<div class="footer row"> 
			<div class='cell'>
			   		<p> This is an autogenerated mail and the sender or the development team doesnot guarantee that the mail is free of any malware, objectionable or damaging content. The views expressed herein no way represents CCMT but solely belong to the sender.<p>

			   		<p align='center'>Mail is sent by <?= Yii::$app->name ?> team. &copy Central Chinmaya Mission Trust 2017 - <?php echo date("Y"); ?> </p>
	   		</div>
   		</div>
   </div>